---
sidebar: sidebar 
permalink: task-s3-enable-data-services.html 
keywords: s3 buckets, s3 storage, s3 working environment, amazon s3 buckets, amazon s3 working environment 
summary: BlueXPでS3バケットを検出したら、ネットアップのデータサービスを使用してバックアップ、階層化、分類、データ同期を実行できます。 
---
= S3バケットでネットアップデータサービスを使用
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXPでS3バケットを検出したら、ネットアップのデータサービスを使用してバックアップ、階層化、分類、データ同期を実行できます。

* BlueXPのバックアップとリカバリ*を使用して、オンプレミスのONTAP システムやCloud Volumes ONTAP システムからS3オブジェクトストレージにデータをバックアップできます。
+
作業を開始するには、キャンバスに移動し、オンプレミスのONTAP またはCloud Volumes ONTAP 作業環境をAmazon S3作業環境にドラッグアンドドロップします。

+
https://["Amazon S3ストレージへのONTAP データのバックアップの詳細については、こちらをご覧ください"^]。

* BlueXP階層化*を使用して、アクセス頻度の低いデータをオンプレミスのONTAP クラスタからS3オブジェクトストレージに階層化できます。
+
作業を開始するには、キャンバスに移動し、オンプレミスのONTAP 作業環境をAmazon S3作業環境にドラッグアンドドロップします。

+
https://["ONTAP データをAmazon S3ストレージに階層化する方法については、こちらをご覧ください"^]。

* BlueXPのコピーと同期*を使用してS3バケットとの間でデータを同期します。
+
作業を開始するには、Canvasに移動し、ソースの作業環境をターゲットの作業環境にドラッグアンドドロップします。Amazon S3作業環境はソースでもターゲットでもかまいません。

+
Amazon S3作業環境を選択し、[サービス]パネルの*[コピーと同期]*をクリックして、S3バケットとの間でデータを同期することもできます。

+
https://["BlueXPのコピーと同期サービスの詳細については、こちらをご覧ください"^]。

* BlueXP分類*を使用してS3バケットをスキャンし、個人データと機密データを検出します。BlueXPの分類では、NetApp解決策 用に作成されたバケットかどうかに関係なく、アカウント内の任意のバケットをスキャンできます。
+
開始するには、Amazon S3作業環境を選択し、[サービス]パネルの*[分類]*セクションから適切なオプションを選択してS3バケットのスキャンを開始します。

+
https://["BlueXP分類サービスの詳細については、こちらをご覧ください"^]。


